---
title: "432 Final Project"
author: 
  - "Tailei Liu"
  - "Annie Gu"
  - "William Zheng"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 1 - Introduction and Motivation

Statistical classification problem has been one of the most important inference tasks in various fields including economy, finance, computer science. With the advancement of technology, modern machine learning based models and large language models excel in classification and motivate many useful applications. In this project, we are interested in traditional statistical model's performance in classification tasks. We apply logistic regression, KNN (explore local similarities), decision tree, ensemble methods, SVM, clustering and neural networks on a dataset that classifies income classes based on 14 features. We present the accuracy of the model and interpretation of their performance.

## Section 2 - Dataset, Summary, and Visualization

In this section we describe the preparation of our data. The input data has been separated into training and test sets by default. 